### ISSUE TITLE
Fonbook Fehler mit Fritz!OS 06.50

### ISSUE THREAD

**Issue by willamowius** [jowi24/kfritz#4] opened 2015-12-18 17:05 UTC
[libfritz++/FritzFonbook.cpp:67] FritzFonbook thread ended
[libfritz++/FritzClient.cpp:318] failed.
[libfritz++/FritzClient.cpp:321] Looking up Phone Settings (using webcm)...
[libfritz++/FritzClient.cpp:329] Exception in connection to fritz.box - Arbitrary error occured
[libfritz++/FritzClient.cpp:329] waiting 60 seconds before retrying

**Comment by jowi24** [comment] 2015-12-30 17:21
Please provide more info regarding the FritzBox model, expected and experienced behaviour in the application.

**Comment by IzzySoft** [comment] 2016-10-17 23:35
Similar issue here: 7390 with FW 6.51

```
"sni-qt/32514" WARN  01:30:29.770 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
[libfritz++/Tools.cpp:101] detected codeset is 'UTF-8'
[libfritz++/FritzClient.cpp:127] requesting login_sid.xml from Fritz!Box.
[libfritz++/FritzClient.cpp:296] Exception in connection to fritz.box - Could not connect
[libfritz++/FritzClient.cpp:296] waiting 30 seconds before retrying
```

And then "eternal loop" of the last 3 lines, never succeeding.

**Expected behavior:** It succeeds connecting and shows the corresponding data in its window. If unable to, it should at least show an error with details ;)

**Experienced behavior:** Window stays empty and user sits in the dark, unless kfritz started from CLI so the errors are displayed.

**Comment by jowi24** [comment] 2016-10-23 14:46
I'm sorry I cannot reproduce the issue. I have also a FB 7390 with same firmware version. My phonebook and call-list are shown correctly in KFritz. Can you provide a full console log including the startup phase of kfritz?

**Comment by IzzySoft** [comment] 2016-10-23 15:14
The above is all I get when starting `kfritz` from a terminal. Or are you talking about a different "console log"?

Ah, btw, what might be relevant: I've just installed kfritz from the "official Ubuntu repo" of precise (12.04), where it's still back on v0.0.8. Your latest release is 0.0.14 as I can see. Is there some `.deb` file you could provide me to try? Or maybe even a PPA? Unfortunately, compiling the latest version from the source myself fails:

<pre>
CMake Error at /usr/share/cmake-2.8/Modules/FindKDE4.cmake:98 (MESSAGE):
  ERROR: cmake/modules/FindKDE4Internal.cmake not found in
  /home/izzy/.kde/share/apps;/usr/share/kde4/apps
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)
-- Configuring incomplete, errors occurred!
make: *** [cmake] Fehler 1
</pre>

Guess that's because I don't have all the KDE DEV packages installed (which would be a bit overhead, as I'm not even running KDE).

**Comment by jowi24** [comment] 2016-10-24 19:48
The old version explains the short console log. You should use the latest version of kfritz for recent fritzbox versions. 

Compiling kfritz requires KDE development headers thats right. However, even if you install them, you won't succeed with ubuntu 12.04, because compiling requires a newer g++ compiler than shipped with 12.04. That is also the reason, why there is no newer kfritz version for this release of ubuntu.

**Comment by IzzySoft** [comment] 2016-10-24 22:16
Yuck. So in other terms: No luck for me until I've setup a new machine (upgrading the current one to 14.04 or up is no option for me for different reasons – and a new machine will be something else than Ubuntu then, but of course still Linux; most likely Mint or some other Debian derivate).

OK, in that case I of course can understand you won't supply a fix for that old version. I'll keep kfritz in mind then to retry once I'm running something more up-to-date here :)

BTW: Are there plans to integrate the answering machine (and maybe fax) with kfritz?

**Comment by jowi24** [comment] 2016-10-25 05:07
Yes. I'm sorry, you are right. Currently its even hard for me to get the time to maintain the current functionality in kfritz, so I don't think that support for answering machine or fax will be integrated.

**Closed as completed by jowi24** 2016-10-25 05:07 UTC
Labels: question

**Comment by IzzySoft** [comment] 2016-10-25 05:55
OK, thanks anyway – especially for taking time you're already short of!
